    import { FormValues } from "@/interfaces/forms";
    import { options1 } from "@/utils/forms/optionsDummies";
    
    export const formTest1: FormValues = {
        formName: "primerAlta",
        formTitle: "Inicio de Sesión",
        action:"POST",
        table: "Usuarios",
        fields: [
        {
            fieldType: "input",
            label: "Nombre de usuario",
            name: "username",
            type: "text",
            subType: "user",
            placeholder: "Escriba su nombre de usuario...",
            autofocus: true,
            required: true,
            //defaultValue: ["JavierDiaz10"],
            value: ["JavierDiaz10"],
            dataType: "varchar",
            campoTabla: "usuario",
        },
        {
            fieldType: "input",
            label: "Password",
            name: "password",
            type: "password",
            subType: "password",
            placeholder: "***...",
            autofocus: false,
            required: true,
            dataType: "varchar",
            campoTabla: "password",
        }, {
            fieldType: "input",
            label: "Mail",
            name: "mail",
            type: "email",
            subType: "email",
            placeholder: "yourname@yourprovider.com...",
            autofocus: false,
            required: false,
            //defaultValue: ["elmaildejavier@hortmail.com"],
            value: ["elmaildejavier@hortmail.com"],
            dataType: "varchar",
            campoTabla: "email",
        },{
            fieldType: "input",
            label: "Número de Cuenta",
            name: "cuenta",
            type: "number",
            subType: "text",
            placeholder: "123456...",
            autofocus: false,
            required: false,
            dataType: "varchar",
            campoTabla: "cuenta",
        },{
            fieldType: "textarea",
            label: "Comentario",
            name: "comentario",
            type: "text",
            subType: "text",
            placeholder: "Aquí su comentario...",
            autofocus: false,
            required: false,
            dataType: "text",
            campoTabla: "comentario",
        },{
            fieldType: "select",
            label: "Selección de Opciones",
            name: "select1",
            type: "text",
            subType: "text",
            placeholder: "Seleccione una...",
            autofocus: false,
            required: false,
            options: options1,
            //defaultValue: ["option2"],
            value: ["option2"],
            dataType: "varchar",
            campoTabla: "opcion",
        },{
            fieldType: "checkbox",
            label: "Opciones para Checkboxes",
            name: "check1",
            type: "text",
            subType: "text",
            placeholder: "Elija más de una de estas...",
            autofocus: false,
            required: false,
            options: options1,
            //defaultValue:["option1", "option3"],
            value:["option1", "option3"],
            dataType: "varchar",
            campoTabla: "opcion2",
        },{
            fieldType: "radio",
            label: "Opciones para Radiobuttons",
            name: "radio1",
            type: "text",
            subType: "text",
            placeholder: "Elija una de estas...",
            autofocus: false,
            required: false,
            options: options1,
            //defaultValue: ["option1"],
            value: ["option1"],
            dataType: "varchar",
            campoTabla: "opcion3",
        },{
            fieldType: "datepicker",
            label: "Fecha de la operación",
            name: "date1",
            type: "text",
            subType: "text",
            placeholder: "Elija una de fecha...",
            autofocus: false,
            required: false,
            //defaultValue: ["1968-05-06T00:00:00"],
            value: ["1968-05-06T00:00:00"],
            dataType: "date",
            campoTabla: "FInicio",
        },
    ],
        buttons: [
            {
            label: "Cancelar",
            type: "reset",
            color: "gray",
        },{
            label: "Iniciar Sesión",
            type: "submit",
            color: "grass",
        },
        ]
    };
