import { FormValues } from "@/interfaces/forms";

export const formUserDataTable: FormValues = {
  formName: "userDataTable",
  formTitle: "Lista de usuarios",
  action: "GET",
  table: "Usuarios",
  fields: [
    {
      fieldType: "input",
      label: "Nombre de usuario",
      name: "username",
      type: "text",
      subType: "user",
      placeholder: "Escriba su nombre de usuario...",
      autofocus: true,
      required: true,
      //value: [""],
      dataType: "varchar",
      campoTabla: "usuario",
      unique: true,
    },
    {
      fieldType: "input",
      label: "Mail",
      name: "mail",
      type: "email",
      subType: "email",
      placeholder: "yourname@yourprovider.com...",
      autofocus: false,
      required: false,
      dataType: "varchar",
      campoTabla: "email",
    },
    {
      fieldType: "datepicker",
      label: "Estado",
      name: "fbaja",
      type: "text",
      subType: "date",
      placeholder: "Fcha de baja...",
      autofocus: false,
      required: false,
      dataType: "date",
      campoTabla: "fechaFin",
    },
  ],
  buttons: [
    {
      label: "Cancelar",
      type: "reset",
      color: "gray",
    },
    {
      label: "Guardar",
      type: "submit",
      color: "grass",
    },
  ],
};
