CREATE DATABASE mitienda;

CREATE TABLE "Productos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "observaciones" varchar(250),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Imagenes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idProducto" int,
  "archivo" varchar(50),
  "observaciones" varchar(250),
  "path" varchar(250),
  "orden" int,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "CategoriasProductos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "idCategoriaPadre" int,
  "categoriaFinal" bool,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Productos_CategoriaProducto" (
  "idProducto" int,
  "idCategoria" int,
  "orden" int,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date,
  PRIMARY KEY ("idProducto", "idCategoria")
);

CREATE TABLE "TiposDatos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Listas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "ListasDetalle" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idLista" int,
  "descripcion" varchar(50),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "AtributosProductos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "idTipoDato" int,
  "idLista" int,
  "idUnidad" int,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Unidades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Productos_AtributosProductos" (
  "idProducto" int,
  "idAtributoProducto" int,
  "valor_texto" varchar(200),
  "valor_entero" int,
  "valor_decimal" float,
  "valor_fecha" date,
  "valor_booleano" bool,
  "idListaDetalle" int,
  "idUnidad" int,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date,
  PRIMARY KEY ("idProducto", "idAtributoProducto")
);

CREATE TABLE "AtributosCategoriasProductos" (
  "idCategoria" int,
  "idAtributo" int,
  "orden" int,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date,
  PRIMARY KEY ("idCategoria", "idAtributo")
);

CREATE TABLE "ListaDePrecios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "observaciones" varchar(250),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Precios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idListaDePrecios" int NOT NULL,
  "idProducto" int NOT NULL,
  "Precio" money DEFAULT 0,
  "idMoneda" int NOT NULL,
  "FechaDesde" date NOT NULL,
  "FechaHasta" date,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Monedas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(20),
  "preferente" bool DEFAULT true,
  "simbolo" varchar(3),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Equivalecnias_Moneda" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idMoneda1" int,
  "factor" float,
  "idMoneda2" int,
  "FInicioVigencia" date,
  "FFinVigencia" date,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario" varchar(20),
  "password" varchar(100),
  "email" varchar(50),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Pedidos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idUsuario" int,
  "idCliente" int,
  "montoInicial" money,
  "descuentoPorc" float,
  "descuentoMonto" money,
  "montoFinal" money,
  "comentario" varchar(500),
  "FechaPedido" timestamptz,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "EstadosPedidos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(20),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Pedidos_EstadosPedidos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idPedido" int,
  "idEstado" int,
  "FechaEstadoPedido" timestamptz,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "PedidosProductos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idPedido" int,
  "idProducto" int,
  "Cantidad" int,
  "montoUnitario" money,
  "montoInicial" money,
  "descuentoPorc" float,
  "descuentoMonto" money,
  "montoFinal" money,
  "comentario" varchar(500),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "EstadosPedidosProductos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(20),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "PedidosProductos_EstadosPedidosProductos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idPedidoProducto" int,
  "idEstadoPedidoProducto" int,
  "FechaEstadoPedidoProducto" timestamptz,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Clientes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "razonSocial" varchar(250),
  "CUIT" int,
  "direccion" varchar(250),
  "TE1" int,
  "TE2" int,
  "mail" varchar(50),
  "observaciones" varchar(250),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "CategoriasClientes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "idCategoriaPadre" int,
  "categoriaFinal" bool,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Clientes_CategoriaCliente" (
  "idCliente" int,
  "idCategoriaCliente" int,
  "orden" int,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date,
  PRIMARY KEY ("idCliente", "idCategoriaCliente")
);

CREATE TABLE "MediosDePago" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "TiposDeIngreso" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Ingresos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idTipoIngreso" int,
  "dCliente" int,
  "monto" money,
  "idMoneda" int,
  "idMedioPago" int,
  "FechaIngreso" timestamptz,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "IngresosPedidos" (
  "idPedido" int,
  "idIngreso" int,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Proveedores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "razonSocial" varchar(250),
  "CUIT" int,
  "direccion" varchar(250),
  "TE1" int,
  "TE2" int,
  "mail" varchar(50),
  "observaciones" varchar(250),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "CategoriasProveedores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "idCategoriaPadre" int,
  "categoriaFinal" bool,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Proveedores_CategoriaProveedor" (
  "idProveedor" int,
  "idCategoriaProveedor" int,
  "orden" int,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date,
  PRIMARY KEY ("idProveedor", "idCategoriaProveedor")
);

CREATE TABLE "Compras" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idUsuario" int,
  "idProveedor" int,
  "montoInicial" money,
  "descuentoPorc" float,
  "descuentoMonto" money,
  "montoFinal" money,
  "comentario" varchar(500),
  "FechaPedido" timestamptz,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "EstadosCompras" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(20),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Compras_EstadosCompras" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idCompra" int,
  "idEstado" int,
  "FechaEstadoCompra" timestamptz,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "ComprasProductos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idCompra" int,
  "idProducto" int,
  "Cantidad" int,
  "precioUnitario" money,
  "precioInicial" money,
  "descuentoPorc" float,
  "descuentoMonto" money,
  "precioFinal" money,
  "comentario" varchar(500),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "EstadosComprasProductos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(20),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "ComprasProductos_EstadosComprasProductos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idCompraProducto" int,
  "idEstadoCompraProducto" int,
  "FechaEstadoCompraProducto" timestamptz,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "TiposDeEgresos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Egresos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idTipoEgreso" int,
  "idProveedor" int,
  "monto" money,
  "idMoneda" int,
  "idMedioPago" int,
  "FechaEgreso" timestamptz,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "EgresosCompras" (
  "idCompra" int,
  "idEgreso" int,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Depositos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "observaciones" varchar(250),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "TiposDeMovimientosStock" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" varchar(50),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "MovimientosStock" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idDeposito" int,
  "idProducto" int,
  "idTipoMovimiento" int,
  "cantidad" int,
  "comentario" varchar(500),
  "FechaMovimiento" timestamptz,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Stock" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idDeposito" int,
  "idProducto" int,
  "cantidad" int,
  "FInicioVigencia" date,
  "FFinVigencia" date,
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Entregas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idPedidoProducto" int,
  "cantidad" int,
  "FechaEntrega" timestamptz,
  "cometario" varchar(500),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

CREATE TABLE "Recepciones" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idComprasProductos" int,
  "cantidad" int,
  "FechaEntrega" timestamptz,
  "cometario" varchar(500),
  "fechaCreacion" timestamptz DEFAULT 'now()',
  "fechaUltimaModificacion" timestamptz,
  "usuarioUltimaModificacion" int,
  "fechaFin" date
);

COMMENT ON COLUMN "TiposDatos"."descripcion" IS 'varchar, int, float, date, bool, list';

COMMENT ON COLUMN "MediosDePago"."descripcion" IS 'Efectivo, Transferencia, Cheque, Tarjeta de Crédito, PagoFacil, Canje';

COMMENT ON COLUMN "TiposDeIngreso"."descripcion" IS 'Cobro, Inversión, Ajuste, Donación';

COMMENT ON COLUMN "TiposDeEgresos"."descripcion" IS 'Pago, Devolución, Ajuste, Pérdida';

COMMENT ON COLUMN "TiposDeMovimientosStock"."descripcion" IS 'Compra, Venta, Préstamo, Rotura, Robo, Regalo, Donación, Ajuste, Transferencia entre depósitos';

ALTER TABLE "Imagenes" ADD FOREIGN KEY ("idProducto") REFERENCES "Productos" ("id");

ALTER TABLE "CategoriasProductos" ADD FOREIGN KEY ("idCategoriaPadre") REFERENCES "CategoriasProductos" ("id");

ALTER TABLE "Productos_CategoriaProducto" ADD FOREIGN KEY ("idProducto") REFERENCES "Productos" ("id");

ALTER TABLE "Productos_CategoriaProducto" ADD FOREIGN KEY ("idCategoria") REFERENCES "CategoriasProductos" ("id");

ALTER TABLE "ListasDetalle" ADD FOREIGN KEY ("idLista") REFERENCES "Listas" ("id");

ALTER TABLE "AtributosProductos" ADD FOREIGN KEY ("idTipoDato") REFERENCES "TiposDatos" ("id");

ALTER TABLE "AtributosProductos" ADD FOREIGN KEY ("idLista") REFERENCES "Listas" ("id");

ALTER TABLE "AtributosProductos" ADD FOREIGN KEY ("idUnidad") REFERENCES "Unidades" ("id");

ALTER TABLE "Productos_AtributosProductos" ADD FOREIGN KEY ("idProducto") REFERENCES "Productos" ("id");

ALTER TABLE "Productos_AtributosProductos" ADD FOREIGN KEY ("idAtributoProducto") REFERENCES "AtributosProductos" ("id");

ALTER TABLE "Productos_AtributosProductos" ADD FOREIGN KEY ("idListaDetalle") REFERENCES "ListasDetalle" ("id");

ALTER TABLE "Productos_AtributosProductos" ADD FOREIGN KEY ("idUnidad") REFERENCES "Unidades" ("id");

ALTER TABLE "AtributosCategoriasProductos" ADD FOREIGN KEY ("idCategoria") REFERENCES "CategoriasProductos" ("id");

ALTER TABLE "AtributosCategoriasProductos" ADD FOREIGN KEY ("idAtributo") REFERENCES "AtributosProductos" ("id");

ALTER TABLE "Precios" ADD FOREIGN KEY ("idListaDePrecios") REFERENCES "ListaDePrecios" ("id");

ALTER TABLE "Precios" ADD FOREIGN KEY ("idProducto") REFERENCES "Productos" ("id");

ALTER TABLE "Precios" ADD FOREIGN KEY ("idMoneda") REFERENCES "Monedas" ("id");

ALTER TABLE "Equivalecnias_Moneda" ADD FOREIGN KEY ("idMoneda1") REFERENCES "Monedas" ("id");

ALTER TABLE "Equivalecnias_Moneda" ADD FOREIGN KEY ("idMoneda2") REFERENCES "Monedas" ("id");

ALTER TABLE "Pedidos" ADD FOREIGN KEY ("idUsuario") REFERENCES "Usuarios" ("id");

ALTER TABLE "Pedidos" ADD FOREIGN KEY ("idCliente") REFERENCES "Clientes" ("id");

ALTER TABLE "Pedidos_EstadosPedidos" ADD FOREIGN KEY ("idPedido") REFERENCES "Pedidos" ("id");

ALTER TABLE "Pedidos_EstadosPedidos" ADD FOREIGN KEY ("idEstado") REFERENCES "EstadosPedidos" ("id");

ALTER TABLE "PedidosProductos" ADD FOREIGN KEY ("idPedido") REFERENCES "Pedidos" ("id");

ALTER TABLE "PedidosProductos" ADD FOREIGN KEY ("idProducto") REFERENCES "Productos" ("id");

ALTER TABLE "PedidosProductos_EstadosPedidosProductos" ADD FOREIGN KEY ("idPedidoProducto") REFERENCES "PedidosProductos" ("id");

ALTER TABLE "PedidosProductos_EstadosPedidosProductos" ADD FOREIGN KEY ("idEstadoPedidoProducto") REFERENCES "EstadosPedidosProductos" ("id");

ALTER TABLE "CategoriasClientes" ADD FOREIGN KEY ("idCategoriaPadre") REFERENCES "CategoriasClientes" ("id");

ALTER TABLE "Clientes_CategoriaCliente" ADD FOREIGN KEY ("idCliente") REFERENCES "Clientes" ("id");

ALTER TABLE "Clientes_CategoriaCliente" ADD FOREIGN KEY ("idCategoriaCliente") REFERENCES "CategoriasClientes" ("id");

ALTER TABLE "Ingresos" ADD FOREIGN KEY ("idTipoIngreso") REFERENCES "TiposDeIngreso" ("id");

ALTER TABLE "Ingresos" ADD FOREIGN KEY ("dCliente") REFERENCES "Clientes" ("id");

ALTER TABLE "Ingresos" ADD FOREIGN KEY ("idMoneda") REFERENCES "Monedas" ("id");

ALTER TABLE "Ingresos" ADD FOREIGN KEY ("idMedioPago") REFERENCES "MediosDePago" ("id");

ALTER TABLE "IngresosPedidos" ADD FOREIGN KEY ("idPedido") REFERENCES "Pedidos" ("id");

ALTER TABLE "IngresosPedidos" ADD FOREIGN KEY ("idIngreso") REFERENCES "Ingresos" ("id");

ALTER TABLE "CategoriasProveedores" ADD FOREIGN KEY ("idCategoriaPadre") REFERENCES "CategoriasProveedores" ("id");

ALTER TABLE "Proveedores_CategoriaProveedor" ADD FOREIGN KEY ("idProveedor") REFERENCES "Proveedores" ("id");

ALTER TABLE "Proveedores_CategoriaProveedor" ADD FOREIGN KEY ("idCategoriaProveedor") REFERENCES "CategoriasProveedores" ("id");

ALTER TABLE "Compras" ADD FOREIGN KEY ("idUsuario") REFERENCES "Usuarios" ("id");

ALTER TABLE "Compras" ADD FOREIGN KEY ("idProveedor") REFERENCES "Proveedores" ("id");

ALTER TABLE "Compras_EstadosCompras" ADD FOREIGN KEY ("idCompra") REFERENCES "Compras" ("id");

ALTER TABLE "Compras_EstadosCompras" ADD FOREIGN KEY ("idEstado") REFERENCES "EstadosCompras" ("id");

ALTER TABLE "ComprasProductos" ADD FOREIGN KEY ("idCompra") REFERENCES "Compras" ("id");

ALTER TABLE "ComprasProductos" ADD FOREIGN KEY ("idProducto") REFERENCES "Productos" ("id");

ALTER TABLE "ComprasProductos_EstadosComprasProductos" ADD FOREIGN KEY ("idCompraProducto") REFERENCES "ComprasProductos" ("id");

ALTER TABLE "ComprasProductos_EstadosComprasProductos" ADD FOREIGN KEY ("idEstadoCompraProducto") REFERENCES "EstadosComprasProductos" ("id");

ALTER TABLE "Egresos" ADD FOREIGN KEY ("idTipoEgreso") REFERENCES "TiposDeEgresos" ("id");

ALTER TABLE "Egresos" ADD FOREIGN KEY ("idProveedor") REFERENCES "Proveedores" ("id");

ALTER TABLE "Egresos" ADD FOREIGN KEY ("idMoneda") REFERENCES "Monedas" ("id");

ALTER TABLE "Egresos" ADD FOREIGN KEY ("idMedioPago") REFERENCES "MediosDePago" ("id");

ALTER TABLE "EgresosCompras" ADD FOREIGN KEY ("idCompra") REFERENCES "Compras" ("id");

ALTER TABLE "EgresosCompras" ADD FOREIGN KEY ("idEgreso") REFERENCES "Egresos" ("id");

ALTER TABLE "MovimientosStock" ADD FOREIGN KEY ("idDeposito") REFERENCES "Depositos" ("id");

ALTER TABLE "MovimientosStock" ADD FOREIGN KEY ("idProducto") REFERENCES "Productos" ("id");

ALTER TABLE "MovimientosStock" ADD FOREIGN KEY ("idTipoMovimiento") REFERENCES "TiposDeMovimientosStock" ("id");

ALTER TABLE "Stock" ADD FOREIGN KEY ("idDeposito") REFERENCES "Depositos" ("id");

ALTER TABLE "Stock" ADD FOREIGN KEY ("idProducto") REFERENCES "Productos" ("id");

ALTER TABLE "Entregas" ADD FOREIGN KEY ("idPedidoProducto") REFERENCES "PedidosProductos" ("id");

ALTER TABLE "Recepciones" ADD FOREIGN KEY ("idComprasProductos") REFERENCES "ComprasProductos" ("id");
